https://www.machinelearningplus.com/python/101-numpy-exercises-python/

### Q. Import numpy as np and print the version number.

In [1]:
import numpy as np
np.version.version

'1.16.5'

### Q. Create a 1D array of numbers from 0 to 9

In [39]:
a = np.array([x for x in range(10)])
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [41]:
# solution
arr =  np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Q. Create a 3×3 numpy array of all True’s

In [7]:
b = np.array([[1]*3]*3,dtype = bool)
b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [8]:
# other solutions
np.full((3, 3), True, dtype=bool) # np.full(shape,value,dtype)
np.ones((3,3), dtype=bool)        # np.ones(shape,dtype)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### Q. Extract all odd numbers from arr

In [15]:
condition = np.mod(arr,2)==1  # ser par,retorna array bool
np.extract(condition,arr)
arr[condition]                # equivalente a linha anterior

array([1, 3, 5, 7, 9])

In [17]:
# other solution
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

### Q. Replace all odd numbers in arr with -1

In [20]:
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### Q. Replace all odd numbers in arr with -1 without changing arr

In [31]:
# solution 
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)  # np.where( condition ,value_if_true ,value_if_false )
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### Q. Convert a 1D array to a 2D array with 2 rows

In [33]:
arr = np.arange(10).reshape((2,5))
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [38]:
# other solution
arr = np.arange(10).reshape((2,-1)) # "-1" automaticamente decide o numero de colunas,generalizando p/ array de n values,n par
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### Q. Stack arrays a and b vertically

In [47]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1) # np.repeat(value,size)

print(a)
print()
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[1 1 1 1 1]
 [1 1 1 1 1]]


In [55]:
np.concatenate((a, b), axis=0) # concat vert : axis default = 0 / concat horz : axis = 1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [53]:
# others solutions
np.vstack([a, b]) # concat vert / see also "np.hstack"

np.r_[a, b]      # concat with the first axis: 0 / see also "np.c_"

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### Q. Stack the arrays a and b horizontally.

In [54]:
np.concatenate((a, b), axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

### Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

In [62]:
a = np.array([1,2,3])
# out : array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [74]:
b = np.repeat(a,3)
c = np.concatenate((b,a,a,a))
c

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [75]:
# other solution
np.r_[np.repeat(a, 3), np.tile(a, 3)] # np.tile(array,times) repeat the whole array

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

### Q. Get the common items between a and b

In [76]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [87]:
c = np.intersect1d(a,b) # np.intersect1d(a1,a2, assume_unique = False)
# assume_unique = True mostrará todas as vezes que os values em comum apareceram
c

array([2, 4])

### Q. From array a remove all items present in array b

In [88]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [92]:
# solution
np.setdiff1d(a,b)

array([1, 2, 3, 4])

### Q. Get the positions where elements of a and b match