### Adendo

In [89]:
import numpy as np
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(a.shape)
print(a.size)

(4, 3)
12


In [88]:
np.linspace(1, 8, num=5)

array([1.  , 2.75, 4.5 , 6.25, 8.  ])

In [70]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [86]:
prod = a * a                          # produto elemento a elemento
prod_mat = np.dot(a,np.transpose(a))  # multiplicação matricial

print(prod)
print(prod_mat)

[[  1   4   9]
 [ 16  25  36]
 [ 49  64  81]
 [100 121 144]]
[[ 14  32  50  68]
 [ 32  77 122 167]
 [ 50 122 194 266]
 [ 68 167 266 365]]


https://www.machinelearningplus.com/python/101-numpy-exercises-python/

### Q. Import numpy as np and print the version number.

In [9]:
import numpy as np
np.version.version

'1.16.5'

### Q. Create a 1D array of numbers from 0 to 9

In [10]:
a = np.array([x for x in range(10)])
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
# solution
arr =  np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Q. Create a 3×3 numpy array of all True’s

In [12]:
b = np.array([[1]*3]*3,dtype = bool)
b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [13]:
# other solutions
np.full((3, 3), True, dtype=bool) # np.full(shape,value,dtype)
np.ones((3,3), dtype=bool)        # np.ones(shape,dtype)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### Q. Extract all odd numbers from arr

In [14]:
condition = np.mod(arr,2)==1  # ser par,retorna array bool
np.extract(condition,arr)
arr[condition]                # equivalente a linha anterior

array([1, 3, 5, 7, 9])

In [15]:
# other solution
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

### Q. Replace all odd numbers in arr with -1

In [16]:
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### Q. Replace all odd numbers in arr with -1 without changing arr

In [17]:
# solution 
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)  # np.where( condition ,value_if_true ,value_if_false )
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### Q. Convert a 1D array to a 2D array with 2 rows

In [90]:
arr = np.arange(10).reshape((2,5))
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
# other solution
arr = np.arange(10).reshape((2,-1)) # "-1" automaticamente decide o numero de colunas,generalizando p/ array de n values,n par
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### Q. Stack arrays a and b vertically

In [20]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1) # np.repeat(value,size)

print(a)
print()
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[1 1 1 1 1]
 [1 1 1 1 1]]


In [21]:
np.concatenate((a, b), axis=0) # concat vert : axis default = 0 / concat horz : axis = 1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [22]:
# others solutions
np.vstack([a, b]) # concat vert / see also "np.hstack"

np.r_[a, b]      # concat with the first axis: 0 / see also "np.c_"

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### Q. Stack the arrays a and b horizontally.

In [23]:
np.concatenate((a, b), axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

### Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

In [24]:
a = np.array([1,2,3])
# out : array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [25]:
b = np.repeat(a,3)
c = np.concatenate((b,a,a,a))
c

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [26]:
# other solution
np.r_[np.repeat(a, 3), np.tile(a, 3)] # np.tile(array,times) repeat the whole array

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

### Q. Get the common items between a and b

In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [28]:
c = np.intersect1d(a,b) # np.intersect1d(a1,a2, assume_unique = False)
# assume_unique = True mostrará todas as vezes que os values em comum apareceram
c

array([2, 4])

### Q. From array a remove all items present in array b

In [29]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [30]:
# solution
np.setdiff1d(a,b)

array([1, 2, 3, 4])

### Q. Get the positions where elements of a and b match

In [31]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [32]:
# solution 
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

### Q. Get all items between 5 and 10 from a.

In [33]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
b = np.where((a>=5) & (a<=10)) # retorna os index e nao os values
b

(array([1, 3, 4], dtype=int64),)

In [34]:
# solution
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

### Q. Convert the function maxx that works on two scalars, to work on two arrays.

In [35]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

In [36]:
def maxx(a,b):
    return np.where(a>b,a,b)

maxx(a,b)

array([6, 7, 9, 8, 9, 7, 5])

In [37]:
# other solution

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

### Q. Swap columns 1 and 2 in the array arr.

In [38]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
# solution
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

### Q. Swap rows 1 and 2 in the array arr:

In [40]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

### Q. Reverse the rows of a 2D array arr.

In [42]:
arr = np.arange(9).reshape(3,-1)

In [43]:
arr[[2,1,0],:]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [44]:
# solution
arr[::-1] 

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

### Q. Reverse the columns of a 2D array arr.

In [45]:
arr = np.arange(9).reshape(3,3)

In [46]:
# solution
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

### Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

In [50]:
np.random.random_sample((5, 3))

array([[1.90229253e-01, 4.53816096e-02, 1.32369519e-01],
       [5.26836811e-01, 8.24197742e-01, 6.46312933e-02],
       [9.48291252e-01, 8.23820635e-04, 5.12538461e-01],
       [1.16042287e-01, 4.75644864e-01, 5.70478009e-01],
       [6.21244920e-03, 6.56230082e-01, 6.30566388e-01]])

In [51]:
# solution
rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
rand_arr = np.random.uniform(5,10, size=(5,3))
print(rand_arr)

[[9.56156005 8.51775468 9.18443933]
 [8.76443357 7.64322935 8.44682434]
 [6.87278149 6.24647697 5.87267895]
 [7.51304069 5.56944999 9.07740985]
 [7.53505816 5.48851217 9.62738055]]


### Q. Print or show only 3 decimal places of the numpy array rand_arr.

In [52]:
rand_arr = np.random.random((5,3))

In [53]:
np.set_printoptions(precision=3)
rand_arr[:]

array([[0.764, 0.053, 0.475],
       [0.712, 0.643, 0.011],
       [0.508, 0.084, 0.934],
       [0.5  , 0.134, 0.729],
       [0.493, 0.092, 0.136]])

### Q. Limit the number of items printed in python numpy array a to a maximum of 6 elements.

In [54]:
a = np.arange(15)

In [55]:
np.set_printoptions(threshold = 6)
a

array([ 0,  1,  2, ..., 12, 13, 14])